# Generated by Django 3.0.8 on 2020-10-18 12:57

from django.db import migrations, models
import django.db.models.deletion
import fontawesome_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('icona', fontawesome_5.fields.IconField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Categories comerç',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Establiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=15)),
                ('telefon1', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adreca', models.CharField(max_length=100)),
                ('reparteix_domicili', models.BooleanField(default=False)),
                ('per_emportar', models.BooleanField(default=False)),
                ('web', models.URLField()),
                ('facebook', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('descripcio', models.TextField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercos.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Dilluns'), (2, 'Dimarts'), (3, 'Dimecres'), (4, 'Dijous'), (5, 'Divendres'), (6, 'Dissabte'), (7, 'Diumenge')])),
                ('from_hour', models.TimeField()),
                ('to_hour', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercos.Establiment')),
            ],
        ),
    ]
