# Generated by Django 3.0.8 on 2020-10-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establiment',
            name='categoria',
        ),
        migrations.AddField(
            model_name='establiment',
            name='categoria',
            field=models.ManyToManyField(to='comercos.Categoria'),
        ),
    ]
