# Generated by Django 3.0.8 on 2020-10-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0002_auto_20201018_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghours',
            name='user',
        ),
        migrations.AddField(
            model_name='establiment',
            name='horaris',
            field=models.ManyToManyField(to='comercos.OpeningHours'),
        ),
    ]
