# Generated by Django 3.0.8 on 2020-10-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0003_auto_20201018_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establiment',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Establiments'},
        ),
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['weekday'], 'verbose_name_plural': 'Horaris'},
        ),
    ]
