# Generated by Django 3.0.8 on 2020-10-18 15:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0004_auto_20201018_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='establiment',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
