# Generated by Django 3.0.8 on 2020-10-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0006_establiment_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establiment',
            name='descripcio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='establiment',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='establiment',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
