# Generated by Django 3.0.8 on 2020-10-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0007_auto_20201018_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establiment',
            old_name='telefon1',
            new_name='mobil',
        ),
    ]
