# Generated by Django 3.0.8 on 2020-10-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0008_auto_20201018_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='establiment',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
