# Generated by Django 3.0.8 on 2020-10-18 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0009_establiment_whatsapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establiment',
            old_name='categoria',
            new_name='categories',
        ),
    ]
