# Generated by Django 3.0.8 on 2020-10-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0010_auto_20201018_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='establiment',
            name='cognoms_propietari',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establiment',
            name='email_propietari',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='establiment',
            name='nom_propietari',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establiment',
            name='tel_propietari',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
