# Generated by Django 3.0.8 on 2020-10-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0011_auto_20201019_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='establiment',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='establiment',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
