# Generated by Django 3.0.8 on 2020-10-20 23:13

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0012_auto_20201020_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='establiment',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '340x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='establiment',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
