# Generated by Django 3.0.8 on 2020-10-22 08:29

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0014_auto_20201021_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establiment',
            name='adreca',
            field=django_google_maps.fields.AddressField(max_length=200),
        ),
        migrations.AlterField(
            model_name='establiment',
            name='location',
            field=django_google_maps.fields.GeoLocationField(default="0,0", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='establiment',
            name='web',
            field=models.URLField(blank=True),
        ),
    ]
