# Generated by Django 3.0.8 on 2020-10-22 09:53

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0015_auto_20201022_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establiment',
            name='adreca',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='establiment',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
