# Generated by Django 3.0.8 on 2020-10-22 10:12

import django.contrib.gis.geos.point
from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0016_auto_20201022_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establiment',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=django.contrib.gis.geos.point.Point(1.861, 41.6674), max_length=63),
        ),
    ]
