# Generated by Django 3.0.8 on 2020-10-22 10:31

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0018_auto_20201022_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establiment',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63),
        ),
    ]
