# Generated by Django 3.0.8 on 2020-10-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0020_auto_20201022_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establiment',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='establiment',
            name='longitude',
        ),
    ]
