# Generated by Django 3.0.8 on 2020-10-22 19:24

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comercos', '0021_auto_20201022_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establiment',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='uploaded_images'),
        ),
    ]
